import {
  Axe,
  Gavel,
  Sword,
  WandSparkles,
  Wand2,
  PenTool,
  Grab,
  Navigation,
  Link as LinkIcon,
  Hammer,
  Swords,
  GripVertical,
  Moon,
  Crosshair,
  Wand,
  Shield,
  ShieldHalf,
  Focus,
  Feather,
  Shirt,
  HardHat,
  Hand,
  Footprints,
  CircleDot,
  Gem,
  RectangleHorizontal,
  Sparkles,
  Fish,
  Wrench,
  Box,
  type LucideIcon,
} from 'lucide-react'

/**
 * Zuordnung der Icon-Schluessel (aus `@/lib/itemGroups`) zu Lucide-Komponenten.
 * `getIcon` liefert bei unbekanntem Schluessel ein neutrales Fallback-Icon.
 */
const ICONS: Record<string, LucideIcon> = {
  axe: Axe,
  gavel: Gavel,
  sword: Sword,
  'wand-sparkles': WandSparkles,
  'wand-2': Wand2,
  'pen-tool': PenTool,
  grab: Grab,
  navigation: Navigation,
  link: LinkIcon,
  hammer: Hammer,
  swords: Swords,
  'grip-vertical': GripVertical,
  moon: Moon,
  crosshair: Crosshair,
  wand: Wand,
  shield: Shield,
  'shield-half': ShieldHalf,
  focus: Focus,
  feather: Feather,
  shirt: Shirt,
  'hard-hat': HardHat,
  hand: Hand,
  footprints: Footprints,
  'circle-dot': CircleDot,
  gem: Gem,
  'rectangle-horizontal': RectangleHorizontal,
  sparkles: Sparkles,
  fish: Fish,
  wrench: Wrench,
  box: Box,
}

export function getIcon(key: string): LucideIcon {
  return ICONS[key] ?? Box
}
